- README.md
- src/index.ts
Adds support for Transporter's `-itc_provider` parameter (see [Transporter documentation](https://help.apple.com/itc/transporteruserguide/#/apdAa073cb45). This parameter is necessary for anyone who is part of multiple development teams in App Store Connect. If this isn't specified for a user with multiple teams, notarization will fail with this error:
> *** Error: Your Apple ID account is attached to other iTunes providers. You will need to specify which
provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)
> Add support for App Store Connect provider

- src/index.ts
#2 
Adding a few seconds of waiting time before making the first call to check the status seems to solve this issue. Please test yourself as well before merging.
> fix: add sleep for apple api lag

- .prettierrc.json
- package.json
- src/helpers.ts
- src/index.ts
- src/spawn.ts
- yarn.lock
I copied the config from `@electron/get`. I did not, however, add a pre-commit hook.
CI support is coming in a future PR, when we add CFA support.
> chore: replace tslint with prettier

- README.md
- src/index.ts
In 2018 Apple introduced the Appstore connect API. This provides a way to use JWT tokens to authenticate.
As I noted in #16 current versions of `altool` also support this way of authenticating. This PR adds the necessary options.
I am not sure what to do about `ascProvider` (aka the `-itc_provider` parameter). It is no longer mentioned in `altool`. Shall we remove it as well?
Closes #16
> feat: support for API Key authentication

- src/index.ts
- src/validate-args.ts
- test/index.test.ts
- test/validate-args.test.ts
Adds validation to authorization args. Effectively moves notarize-specific validation out of electron-packager, but enables others to call `validateAuthorizationArgs` in their own package.
This PR is part of enabling API key auth in electron-packager: https://github.com/electron/electron-packager/pull/1127
This is the first time I'm using TypeScript, so if anything looks off, that's probably why! :smile:
> feat: add validation function for authorizationArgs

- package.json
- yarn.lock
BREAKING CHANGE: Requires Node >= 10.0.0.
> build(deps): upgrade fs-extra to ^9.0.1

- README.md
This is confusing as the AppleID password is a different password. I added clarifying description with a link.
> docs: Clarify appleIdPassword option

- src/index.ts
Zipped file using "zip" is converting UTF-8 NFD charset to UTF-8 NFC. The new APFS filesystem supports both encodings unlike HFS+ where UTF-8 was always converted to UTF-8 NFD. The notarization process may be failed if we keep using "zip".
For more information: https://blog.frostwire.com/2019/08/27/apple-notarization-the-signature-of-the-binary-is-invalid-one-other-reason-not-explained-in-apple-developer-documentation/
> Use ditto instead of zip

- src/notarytool.ts
- src/types.ts
- src/validate-args.ts
When there exists an iCloud keychain, notarytool by default uses that.
The iCloud keychain does not have a local path, and thus cannot be
specified explicitly using --keychain, only implicitly using no
--keychain argument.
Make the opts.keychain argument optional, to allow this (common)
behavior.
> feat: Make --keychain option optional

- src/notarytool.ts
Make Notary Tool file extension agnostic, no need to assume .app extension, for example we may want to notarize .pkg or .dmg
> fix: make notary tool file extension agnostic

- README.md
This is a followup to https://github.com/electron/electron/pull/30740, which makes the hardened runtime entitlements required more clear. 
With modern Electron versions, `com.apple.security.cs.allow-unsigned-executable-memory` is not required and not adding it brings a number of security improvements.
> docs: Improve documentation for macOS entitlements to improve security

- README.md
It took me a little while to find this Team ID and it seems [I'm not the only one](https://github.com/electron/notarize/issues/113), so this change add documentation to help find it.
Resolves #113
> docs: describe how to get the Team ID

- README.md
- src/index.ts
BREAKING CHANGE: users who do not specify tool will not use notarytool by default
> feat: use notarytool by default

- README.md
Since `keychain` option was made optional by #94, update README.
> docs: specify keychain option is optional

- src/notarytool.ts
I tried to sign and notarize my application, but kept getting error `The staple and validate action failed! Error 65.`. It is not obvious why this happens and what does it mean. After some digging I found that the problem is with my certificate. I understand that this is not directly related to this package, but this package could save some time by providing additional information.
Here is the output:
```
...
electron-notarize:notarytool zip succeeded, attempting to upload to Apple +10s
electron-notarize:spawn spawning cmd: xcrun args: [
'notarytool',
'submit',
'/var/folders/jk/arst/T/electron-notarize-QH83Xm/my-app.zip',
'--apple-id',
'*********',
'--password',
'*********',
'--team-id',
'*********',
'--wait',
'--output-format',
'json'
] opts: {} +0ms
electron-notarize:spawn cmd xcrun …
```
> fix: check notarytool response status

- src/notarytool.ts
Alternative to #154 that specifically targets dmg and pkg files.
Created this from comment on #152.
This is currently broken with change #152, as `codesign` doesn't seem to like reading .pkg
> feat: add support for .pkg and .dmg files

- src/check-signature.ts
Skip the codesign verification on `pkg` files because it does not need to be signed to be notarized. Fixes the issue introdocued in https://github.com/electron/notarize/pull/152#issuecomment-1820925064
> fix: skip codesign check on pkg and dmg files

- README.md
- src/index.ts
- src/legacy.ts
- src/types.ts
- src/validate-args.ts
Updated API to reflect deprecated exports.
Updated documentation to match.
Removed code that will no longer work.
> fix: remove now-unusable "legacy" notarization

- .circleci/config.yml
- src/notarytool.ts
Electron builder is not handling responses from notarytool on my device (MacOS Sonoma 14.4.1, XCode 15.2).  The issue is it's trying to JSON.parse a string with the value:
```
Error: HTTP status code: 401. Invalid credentials. Username or password is incorrect. Use the app-specific password generated at appleid.apple.com. Ensure that all authentication arguments are correct.
```
- Fix the ordering of the status code check for the result of `spawn`
- For extra safety, catch errors when `JSON.parse` fails.
```
• electron-builder  version=24.13.3 os=23.4.0
• loaded configuration  file=/Users/connormeehan/projects/eyejack/eyejack-creator/electron-builder.config.js
• description is missed in the package.json  appPackageFile=/Users/connormeehan/projects/eyejack/eyejack-creator/dist_electron/bund …
```
> fix: Brittle response parsing from notarytool

- .gitignore
- .prettierrc.json
- README.md
- package.json
- src/check-signature.ts
- src/index.ts
- src/staple.ts
- src/types.ts
- src/validate-args.ts
- typedoc.json
- yarn.lock
Similar to electron/osx-sign#320 but for notarize.
Significant changes:
* Removal of `NotarizeStapleOptions` which is functionally identical to `NotaryToolNotarizeAppOptions`.
* Added details on keychain credential authentication and debugging notarization credentials
* Added more usage examples with each authentication strategy
See preview: https://erickzhao.github.io/notarize/
> docs: clean up types and add API docs site

- src/notarytool.ts
Closes #139
Also adds the nice touch of adding the notarization job ID to debug logs as well
> feat: add notarization logs to debug logging for success

- README.md
- src/index.ts
- src/notarytool.ts
- src/types.ts
More info in the linked issue: closes #200
> feat: allow notarization on macOS versions down to 10.15

- README.md
docs: Mark custom notarytoolPath as unsupported
> docs: Mark custom notarytoolPath as unsupported

- .github/workflows/docs.yml
- package.json
Adds a GitHub Action to generate TypeDoc API documentation and upload it to Azure Blob Storage with an SAS token.
See example run on my fork: https://github.com/erickzhao/notarize/actions/runs/11863393596/job/33064761419
> build: publish API documentation

- package.json
- src/helpers.ts
- src/notarytool.ts
- src/spawn.ts
- yarn.lock
> build: update prettier to 3.4.2

- package.json
- src/check-signature.ts
- src/helpers.ts
- src/staple.ts
- test/helpers.test.ts
- yarn.lock
Closes #227
Uses `node:fs` directly instead of routing `graceful-fs` through `util.promisify`.
* Works around the issue where `import * as fs from 'graceful-fs'` would make the `fs` syntax look like `fs.default.fn()` instead of `fs.fn()`.
* `graceful-fs` doesn't patch `fs.rm` nor `fs.mkdtemp`, so it's safe to remove the package altogether and preserve previous behaviour.
* Adds a small unit test for the `withTempDir` helper, although I think `vitest` magic makes it so that the test passes even with the faulty runtime import.
cc @ckerr @erikian
> fix: remove `graceful-fs` and use direct imports

- README.md
> chore: fix minor typo in README.md

- src/index.ts
Exports all types that are exported by `types.ts` so we can reference them in other packages (e.g. `@electron/packager`).
> fix: export all relevant types from package
